/*
 * Dark Souls 3 - Open Server
 * Copyright (C) 2021 Tim Leonard
 *
 * This program is free software; licensed under the MIT license.
 * You should have received a copy of the license along with this program.
 * If not, see <https://opensource.org/licenses/MIT>.
 */

ENTRY(None,                                                       "None",                                                     0)
ENTRY(Blade_of_the_Darkmoon,                                      "Blade of the Darkmoon",                                    1)
ENTRY(Warriors_of_sunlight,                                       "Warriors of sunlight",                                     2)
ENTRY(Mound_Makers,                                               "Mound Makers",                                             3)
ENTRY(Spears_of_the_Church,                                       "Spears of the Church",                                     4)
ENTRY(Fingers_of_Rosaria,                                         "Fingers of Rosaria",                                       5)
ENTRY(Watchdogs_of_Farron,                                        "Watchdogs of Farron",                                      6)
ENTRY(Aldrich_Faithfuls,                                          "Aldrich Faithfuls",                                        7)
ENTRY(Way_of_Blue,                                                "Way of Blue",                                              8)
ENTRY(Blue_Sentinels,                                             "Blue Sentinels",                                           9)