/*
 * Dark Souls 3 - Open Server
 * Copyright (C) 2021 Tim Leonard
 *
 * This program is free software; licensed under the MIT license.
 * You should have received a copy of the license along with this program.
 * If not, see <https://opensource.org/licenses/MIT>.
 */

ENTRY(none,                                                     "",                                                         0)
ENTRY(and_then,                                                 "and then",                                                 0xC350)
ENTRY(but,                                                      "but",                                                      0xC351)
ENTRY(therefore,                                                "therefore",                                                0xC352)
ENTRY(in_short,                                                 "in short",                                                 0xC353)
ENTRY(_or,                                                      "or",                                                       0xC354)
ENTRY(only,                                                     "only",                                                     0xC355)
ENTRY(by_the_way,                                               "by the way",                                               0xC356)
ENTRY(so_to_speak,                                              "so to speak",                                              0xC357)
ENTRY(all_the_more,                                             "all the more",                                             0xC358)
ENTRY(fullstop,                                                 ".",                                                        0xC359)
