/*
 * Dark Souls 3 - Open Server
 * Copyright (C) 2021 Tim Leonard
 *
 * This program is free software; licensed under the MIT license.
 * You should have received a copy of the license along with this program.
 * If not, see <https://opensource.org/licenses/MIT>.
 */

ENTRY(Host,                                                     "Host",                                                0)
ENTRY(Summon_White,                                             "White",                                               1)
ENTRY(Summon_Red,                                               "Red",                                                 2)
ENTRY(Invade_Red,                                               "Red",                                                 3)
ENTRY(Summon_Purple_White,                                      "Mound Maker",                                         4)
ENTRY(Covenant_Spear_of_the_Church,                             "Spear of the Church",                                 6)
ENTRY(Covenant_Blade_of_the_Darkmoon,                           "Blade of the Darkmoon",                               7)
ENTRY(Guardian_of_Rosaria,                                      "Guardian of Rosaria",                                 8)
ENTRY(Covenant_Watchdog_of_Farron,                              "Watchdog of Farron",                                  9)
ENTRY(Covenant_Aldrich_Faithful,                                "Aldrich Faithful",                                    10)
ENTRY(Avatar,                                                   "Avatar",                                              11)
ENTRY(Arena_Battle_Royal,                                       "Arena Battle",                                        12)
ENTRY(Umbasa_White,                                             "Umbasa White",                                        13)
ENTRY(Summon_Sunlight_White,                                    "Sunlight White",                                      14)
ENTRY(Summon_Sunlight_Dark,                                     "Sunlight Dark",                                       15)
ENTRY(Summon_Purple_Dark,                                       "Sunlight Purple Dark",                                16)
ENTRY(Invade_Sunlight_Dark,                                     "Sunlight Dark",                                       17)
ENTRY(Invade_Purple_Dark,                                       "Purple Dark",                                         18)
ENTRY(Force_Join_Session,                                       "Force Join Session",                                  19)
ENTRY(Red_Hunter,                                               "Red Hunter",                                          20)
ENTRY(Blue_Sentinel,                                            "Blue Sentinel",                                       21)



