/*
 * Dark Souls 3 - Open Server
 * Copyright (C) 2021 Tim Leonard
 *
 * This program is free software; licensed under the MIT license.
 * You should have received a copy of the license along with this program.
 * If not, see <https://opensource.org/licenses/MIT>.
 */

ENTRY(blank_ahead,                                                  "%s ahead",                                                 0x2710)
ENTRY(no_blank_ahead,                                               "No %s ahead",                                              0x2711)
ENTRY(blank_required_ahead,                                         "%s required ahead",                                        0x2712)
ENTRY(be_wary_of_blank,                                             "by wary of %s",                                            0x2713)
ENTRY(try_blank,                                                    "try %s",                                                   0x2714)
ENTRY(could_this_be_blank,                                          "Could this be a %s?",                                      0x2715)
ENTRY(if_only_i_had_a_blank,                                        "If only I had a %s...",                                    0x2716)
ENTRY(visions_of_blank,                                             "visions of %s...",                                         0x2717)
ENTRY(time_for_blank,                                               "Time for %s",                                              0x2718)
ENTRY(blank,                                                        "%s",                                                       0x2719)
ENTRY(blank_exclamation,                                            "%s!",                                                      0x271A)
ENTRY(blank_question,                                               "%s?",                                                      0x271B)
ENTRY(blank_ellipsis,                                               "%s...",                                                    0x271C)
ENTRY(huh_its_a_blank,                                              "Huh. It's a %s...",                                        0x271D)
ENTRY(praise_the_blank,                                             "praise the %s!",                                           0x271E)
ENTRY(let_there_be_blank,                                           "Let there be %s",                                          0x271F)
ENTRY(ahh_blank,                                                    "Ahh. %s...",                                               0x2720)