/*
 * Dark Souls 3 - Open Server
 * Copyright (C) 2021 Tim Leonard
 *
 * This program is free software; licensed under the MIT license.
 * You should have received a copy of the license along with this program.
 * If not, see <https://opensource.org/licenses/MIT>.
 */

ENTRY(Ashen_Grave,                                                "Ashen Grave",                                              0)
ENTRY(Firelink_Shrine,                                            "Firelink Shrine",                                          4001950)      // Also 3001960
ENTRY(Cemetery_of_Ash,                                            "Cemetery of Ash",                                          4001951)
ENTRY(Iudex_Gundyr,                                               "Iudex Gundyr",                                             4001952)
ENTRY(Untended_Graves,                                            "Untended Graves",                                          4001953)
ENTRY(Champion_Gundyr,                                            "Champion Gundyr",                                          4001954)

ENTRY(High_Wall_of_Lothric,                                       "High Wall of Lothric",                                     3001950)
ENTRY(Oceiros_the_Consumed_King,                                  "Oceiros, the Consumed King",                               3001951)
ENTRY(Vordt_of_the_Boreal_Valley,                                 "Vordt of the Boreal Valley",                               3001952)
ENTRY(Dancer_of_the_Boreal_Valley,                                "Dancer of the Boreal Valley",                              3001954)
ENTRY(Tower_on_the_Wall,                                          "Tower on the Wall",                                        3001955)

ENTRY(High_Wall_of_Lothric_Teleport,                              "High Wall of Lothric, Teleport",                           0)
ENTRY(Undead_Settlement,                                          "Undead Settlement",                                        3101950)
ENTRY(Pit_of_Hollows,                                             "Pit of Hollows",                                           3101951)
ENTRY(Cliff_Underside,                                            "Cliff Underside",                                          3101952)
ENTRY(Dilipidated_Bridge,                                         "Dilipidated Bridge",                                       3101953)
ENTRY(Foot_of_the_High_Wall,                                      "Foot of the High Wall",                                    3101954)

ENTRY(Halfway_Fortress,                                           "Halfway Fortress",                                         3301950)
ENTRY(Abyss_Watchers,                                             "Abyss Watchers",                                           3301951)
ENTRY(Crystal_Sage,                                               "Crystal Sage",                                             3301952)
ENTRY(Farron_Keep,                                                "Farron Keep",                                              3301953)
ENTRY(Keep_Ruins,                                                 "Keep Ruins",                                               3301954)
ENTRY(Old_Wolf_of_Farron,                                         "Old Wolf of Farron",                                       3301955)
ENTRY(Road_of_Sacrifices,                                         "Road of Sacrifices",                                       3301956)
ENTRY(Crucifixion_Woods,                                          "Crucifixion Woods",                                        3301957)
ENTRY(Farron_Keep_Perimeter,                                      "Farron Keep Perimeter",                                    3301958)

ENTRY(Cleansing_Chapel,                                           "Cleansing Chapel",                                         3501950)
ENTRY(Deacons_of_the_Deep,                                        "Deacons of the Deep",                                      3501951)
ENTRY(Rosarias_Bed_Chamber,                                       "Rosaria's Bed Chamber",                                    3501952)
ENTRY(Cathedral_of_the_Deep,                                      "Cathedral of the Deep",                                    3501953)

ENTRY(Catacombs_of_Carthus,                                       "Catacombs of Carthus",                                     3801956)
ENTRY(High_Lord_Wolnir,                                           "High Lord Wolnir",                                         3801950)
ENTRY(Abandoned_Tomb,                                             "Abandoned Tomb",                                           3801951)
ENTRY(Old_Kings_Antechamber,                                      "Old King's Antechamber",                                   3801952)
ENTRY(Demon_Ruins,                                                "Demon Ruins",                                              3801953)
ENTRY(Old_Demon_King,                                             "Old Demon King",                                           3801954)

ENTRY(Irithyll_of_the_Boreal_valley,                              "Irithyll of the Boreal valley",                            3701957)
ENTRY(Central_Irithyll,                                           "Central Irithyll",                                         3701954)
ENTRY(Church_of_Yorshka,                                          "Church of Yorshka",                                        3701950)
ENTRY(Distant_Manor,                                              "Distant Manor",                                            3701955)
ENTRY(Pontiff_Sulyvahn,                                           "Pontiff Sulyvahn",                                         3701951)
ENTRY(Water_Reserve,                                              "Water Reserve",                                            3701956)
ENTRY(Anor_Londo,                                                 "Anor Londo",                                               3701953)
ENTRY(Prison_Tower,                                               "Prison Tower",                                             3701958)
ENTRY(Aldrich_Devourer_of_Gods,                                   "Aldrich, Devourer of Gods",                                3701952)

ENTRY(Irithyll_Dungeon,                                           "Irithyll Dungeon",                                         3901950)
ENTRY(Profaned_Capital,                                           "Profaned Capital",                                         3901952)
ENTRY(Yhorm_The_Giant,                                            "Yhorm The Giant",                                          3901951)

ENTRY(Lothric_Castle,                                             "Lothric Castle",                                           3011950)
ENTRY(Dragon_Barracks,                                            "Dragon Barracks",                                          3011952)
ENTRY(Dragonslayer_Armour,                                        "Dragonslayer Armour",                                      3011951)
ENTRY(Grand_Archives,                                             "Grand Archives",                                           3411951)
ENTRY(Twin_Princes,                                               "Twin Princes",                                             3411950)

ENTRY(Archdragon_Peak,                                            "Archdragon Peak",                                          3201950)
ENTRY(Dragon_Kin_Mausoleum,                                       "Dragon-Kin Mausoleum",                                     3201953)
ENTRY(Great_Belfry,                                               "Great Belfry",                                             3201952)
ENTRY(Nameless_King,                                              "Nameless King",                                            3201951)

ENTRY(Flameless_Shrine,                                           "Flameless Shrine",                                         4101950)
ENTRY(Klin_of_the_First_Flame,                                    "Klin of the First Flame",                                  4101951)
ENTRY(Soul_of_Cinder,                                             "Soul of Cinder",                                           4101952)

ENTRY(Snowfield,                                                  "Snowfield",                                                4501951)
ENTRY(Rope_Bridge_Cave,                                           "Rope Bridge Cave",                                         4501952)
ENTRY(Corvian_Settlement,                                         "Corvian Settlement",                                       4501953)
ENTRY(Snowy_Mountain_Pass,                                        "Snowy Mountain Pass",                                      4501954)
ENTRY(Ariandel_Chapel,                                            "Ariandel Chapel",                                          4501955)
ENTRY(Sister_Friede,                                              "Sister Friede",                                            4501950)
ENTRY(Depths_of_the_Painting,                                     "Depths of the Painting",                                   4501957)
ENTRY(Champions_Gravetender,                                      "Champion's Gravetender",                                   4501956)

ENTRY(The_Dreg_Heap,                                              "The Dreg Heap",                                            5001951)
ENTRY(Earthen_Peak_Ruins,                                         "Earthen Peak Ruins",                                       5001952)
ENTRY(Within_the_Earthen_Peak_Ruins,                              "Within the Earthen Peak Ruins",                            5001953)
ENTRY(The_Demon_Prince,                                           "The Demon Prince",                                         5001950)

ENTRY(The_Ringed_City,                                            "The Ringed City",                                          0)
ENTRY(Mausoleum_Lookout,                                          "Mausoleum Lookout",                                        5101952)
ENTRY(Ringed_Inner_Wall,                                          "Ringed Inner Wall",                                        5101953)
ENTRY(Ringed_City_Streets,                                        "Ringed City Streets",                                      5101954)
ENTRY(Shared_Grave,                                               "Shared Grave",                                             5101955)
ENTRY(Church_of_Filianore,                                        "Church of Filianore",                                      5101950)
ENTRY(Filianores_rest,                                            "Filianore's rest",                                         5111951)
ENTRY(Slave_Knight_Gael,                                          "Slave Knight Gael",                                        0)
ENTRY(Darkeater_Midir,                                            "Darkeater Midir",                                          5101951)