/*
 * Dark Souls 3 - Open Server
 * Copyright (C) 2021 Tim Leonard
 *
 * This program is free software; licensed under the MIT license.
 * You should have received a copy of the license along with this program.
 * If not, see <https://opensource.org/licenses/MIT>.
 */

ENTRY(White_Phantom,                                              "White Phantom",                                            1)
ENTRY(Dark_Spirit,                                                "Dark Spirit",                                              2)
ENTRY(Ghost_1,                                                    "Ghost",                                                    3)
ENTRY(Ghost_2,                                                    "Ghost",                                                    4)
ENTRY(Hollow,                                                     "Hollow",                                                   8)
ENTRY(Transparent,                                                "Transparent",                                              10)
ENTRY(Invisible,                                                  "Invisible",                                                11)
ENTRY(Dragon,                                                     "Dragon",                                                   12)
ENTRY(Arena,                                                      "Arena",                                                    13)