/*
 * Dark Souls 3 - Open Server
 * Copyright (C) 2021 Tim Leonard
 *
 * This program is free software; licensed under the MIT license.
 * You should have received a copy of the license along with this program.
 * If not, see <https://opensource.org/licenses/MIT>.
 */

ENTRY(None,                                                       "None",                                                     0)
ENTRY(Host,                                                       "Host",                                                     1)
ENTRY(Phantom,                                                    "Phantom",                                                  2)
ENTRY(Black_Phantom,                                              "Black Phantom",                                            3)
ENTRY(Hollow,                                                     "Hollow",                                                   4)
ENTRY(Enemy,                                                      "Enemy",                                                    6)
ENTRY(Boss_Giants_And_Big_Lizard,                                 "Boss (giants, big lizard)",                                7)
ENTRY(Friend,                                                     "Friend",                                                   8)
ENTRY(Angry_Friend,                                               "Angry Friend",                                             9)
ENTRY(Decoy_Enemy,                                                "Decoy Enemy",                                              10)
ENTRY(Blood_Child,                                                "Blood Child",                                              11)
ENTRY(Battle_Friend,                                              "Battle Friend",                                            12)
ENTRY(Dragon,                                                     "Dragon",                                                   13)
ENTRY(Dark_Spirit,                                                "Dark Spirit",                                              16)
ENTRY(Watchdog_of_Farron,                                         "Watchdog of Farron",                                       17)
ENTRY(Aldrich_Faithful,                                           "Aldrich Faithful",                                         18)
ENTRY(Darkwraiths,                                                "Darkwraiths",                                              24)
ENTRY(NPC,                                                        "NPC",                                                      26)
ENTRY(Hostile_NPC,                                                "Hostile NPC",                                              27)
ENTRY(Arena,                                                      "Arena",                                                    29)
ENTRY(Mad_Phantom,                                                "Mad Phantom",                                              31)
ENTRY(Mad_Spirit,                                                 "Mad Spirit",                                               32)
ENTRY(Giant_Crabs_And_Dragons,                                    "Giant crabs,Dragons from Lothric castle",                  33)