/*
 * Dark Souls 3 - Open Server
 * Copyright (C) 2021 Tim Leonard
 *
 * This program is free software; licensed under the MIT license.
 * You should have received a copy of the license along with this program.
 * If not, see <https://opensource.org/licenses/MIT>.
 */

ENTRY(normal,                                                       "",                                                     0x00)
ENTRY(point_forward,                                                "Point forward",                                        0x01)
ENTRY(point_up,                                                     "Point up",                                             0x02)
ENTRY(point_down,                                                   "Point down",                                           0x03)
ENTRY(wave,                                                         "Wave",                                                 0x04)
ENTRY(beckon,                                                       "Beckon",                                               0x05)
ENTRY(call_over,                                                    "Call over",                                            0x06)
ENTRY(welcome,                                                      "Welcome",                                              0x07)
ENTRY(applause,                                                     "Applause",                                             0x08)
ENTRY(quiet_resolve,                                                "Quiet Resolve",                                        0x09)
ENTRY(jump_for_joy,                                                 "Jump for joy",                                         0x0A)
ENTRY(joy,                                                          "Joy",                                                  0x0B)
ENTRY(rejoice,                                                      "Rejoice",                                              0x0C)
ENTRY(hurrah,                                                       "Hurrah",                                               0x0D)
ENTRY(praise_the_sun,                                               "Praise the sun",                                       0x0E)
ENTRY(my_thanks,                                                    "My thanks",                                            0x0F)
ENTRY(bow,                                                          "Bow",                                                  0x10)
ENTRY(proper_bow,                                                   "Proper bow",                                           0x11)
ENTRY(dignified_bow,                                                "Dignified bow",                                        0x12)
ENTRY(duel_bow,                                                     "Dual bow",                                             0x13)
ENTRY(legion_etiquette,                                             "Legion Etiquette",                                     0x14)
ENTRY(darkmoon_loyalty,                                             "Darkmoon Loyalty",                                     0x15)
ENTRY(be_my_sword,                                                  "Be my sword",                                          0x16)
ENTRY(prayer,                                                       "Player",                                               0x17)
ENTRY(silent_ally,                                                  "Silent ally",                                          0x18)
ENTRY(rest,                                                         "Rest",                                                 0x19)
ENTRY(collapse,                                                     "Collapse",                                             0x1A)
ENTRY(patches_squat,                                                "Patches squat",                                        0x1B)
ENTRY(prostration,                                                  "Prostration",                                          0x1C)
ENTRY(toast,                                                        "Toast",                                                0x1D)
ENTRY(sleep,                                                        "Sleep",                                                0x1E)
ENTRY(curl_up,                                                      "Curl up",                                              0x1F)
ENTRY(stretch_out,                                                  "Stretch out",                                          0x20)
ENTRY(path_of_the_dragon,                                           "Path of the dragon",                                   0x21)