/*
 * Dark Souls 3 - Open Server
 * Copyright (C) 2021 Tim Leonard
 *
 * This program is free software; licensed under the MIT license.
 * You should have received a copy of the license along with this program.
 * If not, see <https://opensource.org/licenses/MIT>.
 */

ENTRY(Spear_of_the_Church,				"Spear of the Church (Player Version)",																							30000)
ENTRY(Vordt_of_the_Boreal_Valley,		"Vordt of the Boreal Valley",															3000800)
ENTRY(Oceiros_the_Consumed_King,		"Oceiros, the Consumed King",															3000830)
ENTRY(Dancer_of_the_Boreal_Valley,		"Dancer of the Boreal Valley",															3000899)
ENTRY(Dragonslayer_Armour,				"Dragonslayer Armour",																	3010800)
ENTRY(Curse_rotted_Greatwood,			"Curse-rotted Greatwood",																3100800)
ENTRY(Ancient_Wyvern,					"Ancient Wyvern",																		3200800)
ENTRY(King_of_the_Storm,				"King of the Storm",																	3200850)
ENTRY(Nameless_King,					"Nameless King",																		3200851)
ENTRY(Abyss_Watchers,					"Abyss Watchers",																		3300801)
ENTRY(Crystal_Sage,						"Crystal Sage",																			3300850)
ENTRY(Lorian_Elder_Prince,				"Lorian, Elder Prince",																	3410830)
ENTRY(Lothric_Younger_Prince,			"Lothric, Younger Prince",																3410831)
ENTRY(Lorian_Elder_Prince_2,			"Lorian, Elder Prince",																	3410832)
ENTRY(Deacons_of_the_Deep,				"Deacons of the Deep",																	3500800)
ENTRY(BETA_Oceiros,				        "BETA: Oceiros you would have fought in cut Grave of God map",							3600800)
ENTRY(BETA_CrimsonBat,			        "BETA: Crimson Bat you would have fought in cut Grave of God map",						3600850)
ENTRY(Aldrich_Devourer_Of_Gods,			"Aldrich, Devourer of Gods",															3700800)
ENTRY(Pontiff_Sulyvahn,					"Pontiff Sulyvahn",																		3700850)
ENTRY(High_Lord_Wolnir,					"High Lord Wolnir",																		3800800)
ENTRY(Old_Demon_King,					"Old Demon King",																		3800830)
ENTRY(Yhorm_the_Giant,					"Yhorm the Giant",																		3900800)
ENTRY(Iudex_Gundyr,						"Iudex Gundyr",																			4000800)
ENTRY(Champion_Gundyr,					"Champion Gundyr",																		4000830)
ENTRY(Soul_Of_Cinder,					"Soul of Cinder",																		4100800)
ENTRY(Blackflame_Friede,				"Blackflame Friede",																	4500800)
ENTRY(Sister_Friede,					"Sister Friede",																		4500801)
ENTRY(Father_Ariandel_And_Friede,		"Father Ariandel and Friede",															4500802)
ENTRY(Gravetender_Greatwolf,			"Gravetender Greatwolf",																4500861)
ENTRY(Demon_From_Below,				    "Demon from Below",                                                                     5000801)
ENTRY(Demon_In_Pain,					"Demon in Pain",                                                                        5000802)
ENTRY(Halflight,						"Halflight, Spear of the Church",														5100800)
ENTRY(Darkeater_Midir,				    "Darkeater Midir",																		5100850)
ENTRY(Slave_Knight_Gael,				"Slave Knight Gael",																	5110800)