// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Shared_FpdLogMessage.proto

#ifndef PROTOBUF_Shared_5fFpdLogMessage_2eproto__INCLUDED
#define PROTOBUF_Shared_5fFpdLogMessage_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
// @@protoc_insertion_point(includes)

namespace Shared_FpdLogMessage {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_Shared_5fFpdLogMessage_2eproto();
void protobuf_AssignDesc_Shared_5fFpdLogMessage_2eproto();
void protobuf_ShutdownFile_Shared_5fFpdLogMessage_2eproto();


// ===================================================================


// ===================================================================


// ===================================================================


// @@protoc_insertion_point(namespace_scope)

}  // namespace Shared_FpdLogMessage

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_Shared_5fFpdLogMessage_2eproto__INCLUDED
