/*
 * Dark Souls 3 - Open Server
 * Copyright (C) 2021 Tim Leonard
 *
 * This program is free software; licensed under the MIT license.
 * You should have received a copy of the license along with this program.
 * If not, see <https://opensource.org/licenses/MIT>.
 */

 /*
 00000000:None
00000A5A:Fire Keepers' Dwelling
0000122A:The Far Fire
000029AE:The Crestfallen's Retreat
0000299F:Cardinal Tower
000029A4:Soldiers' Rest
000029B3:The Place Unbeknownst
00007BA7:Heide's Ruin
00007BA2:Tower of Flame
00007BAC:The Blue Cathedral
000048DA:Unseen Path to Heide
0000410F:Exile Holding Cells
0000411E:McDuff's Workshop
00004123:Servants' Quarters
0000410A:Straid's Cell
00004114:The Tower Apart
0000412D:The Saltfort
00004119:Upper Ramparts
00005C62:Undead Refuge
00005C67:Bridge Approach
00005C6C:Undead Lockaway
00005C71:Undead Purgatory
00004501:Poison Pool
000044F2:The Mines
000044F7:Lower Earthen Peak
00004506:Central Earthen Peak
0000450B:Upper Earthen Peak
00004CC7:Threshold Bridge
00004CC2:Ironhearth Hall
00004CCC:Eygil's Idol
00004CD1:Belfry Sol Approach
000073D2:Old Akelarre
00007F8F:Ruined Fork Road
00007F94:Shaded Ruins
00008377:Gyrm's Respite
0000837C:Ordeal's End
0000393F:Royal Army Campsite
00003944:Chapel Threshold
0000393A:Lower Brightstone Cove
0000875F:Harval's Resting Place
0000875A:Grave Entrance
00006441:Upper Gutter
00006437:Central Gutter
00006432:Black Gulch Mouth
0000643C:Hidden Chamber
00005492:King's Gate
000054A1:Under Castle Drangleic
00005497:Central Castle Drangleic
0000549C:Forgotten Chamber
00002D82:Tower of Prayer
00002D87:Crumbled Ruins
00002D8C:Rhoy's Resting Place
00002D91:Bonfire
00002D96:Rise of the Dead
0000604F:Undead Crypt Entrance
0000604A:Undead Ditch
00003D22:Foregarden
00003D27:Ritual Site
00006C02:Dragon Aerie
00006C07:Shrine Entrance
00008B42:Sanctum Walk
00008B65:Tower of Prayer
00008B47:Priestess' Chamber
00008B56:Hidden Sanctum Chamber
00008B5B:Lair of the Imperfect
00008B60:Sanctum Interior
00008B51:Sanctum Nadir
00008F2A:Throne Floor
00008F34:Upper Floor
00008F2F:Foyer
00008F3E:Lowermost Floor
00008F43:The Smelter Throne
00008F39:Iron Hallway Entrance
00009312:Outer Wall
0000931C:Abandoned Dwelling
0000932B:Expulsion Chamber
00009335:Inner Wall
00009321:Lower Garrison
00009326:Grand Cathedral
 */