/*
 * Dark Souls 3 - Open Server
 * Copyright (C) 2021 Tim Leonard
 *
 * This program is free software; licensed under the MIT license.
 * You should have received a copy of the license along with this program.
 * If not, see <https://opensource.org/licenses/MIT>.
 */

ENTRY(None,                                                       "None",                                                     0)
ENTRY(Heirs_of_the_Sun,                                           "Heirs of the Sun",                                         1)
ENTRY(Blue_Sentinels,                                             "Blue Sentinels",                                           2)
ENTRY(Brotherhood_of_Blood,                                       "Brotherhood of Blood",                                     3)
ENTRY(Way_of_Blue,                                                "Way of Blue",                                              4)
ENTRY(Rat_King_Covenant,                                          "Rat King Covenant",                                        5)
ENTRY(Bell_Keepers,                                               "Bell Keepers",                                             6)
ENTRY(Dragon_Remnants,                                            "Dragon Remnants",                                          7)
ENTRY(Company_of_Champions,                                       "Company of Champions",                                     8)	
ENTRY(Pilgrims_of_Dark,                                           "Pilgrims of Dark",                                         9)