/*
 * Dark Souls 3 - Open Server
 * Copyright (C) 2021 Tim Leonard
 *
 * This program is free software; licensed under the MIT license.
 * You should have received a copy of the license along with this program.
 * If not, see <https://opensource.org/licenses/MIT>.
 */

ENTRY(Nothing,                                                    "Nothing",                      -1)
ENTRY(Point,                                                      "Point",                        10)
ENTRY(I_wont_Bite,                                                "I won't Bite",                 20)
ENTRY(Bow,                                                        "Bow",                          30)
ENTRY(Welcome,                                                    "Welcome",                      40)
ENTRY(Duel_bow,                                                   "Duel bow",                     50)
ENTRY(Wave,                                                       "Wave",                         60)
ENTRY(Joy,                                                        "Joy",                          70)
ENTRY(Righty_ho,                                                  "Righty-ho",                    80)
ENTRY(No_way,                                                     "No way",                       90)
ENTRY(This_ones_me,                                               "This one's me",                100)
ENTRY(Hurrah,                                                     "Hurrah",                       120)
ENTRY(Have_mercy,                                                 "Have mercy",                   130)
ENTRY(Decapitate,                                                 "Decapitate",                   150)
ENTRY(Mock,                                                       "Mock",                         220)
ENTRY(Pumped_up,                                                  "Pumped up",                    240)
ENTRY(Prostration,                                                "Prostration",                  250)
ENTRY(Warmup,                                                     "Warmup",                       270)
ENTRY(Warcry,                                                     "Warcry",                       280)
ENTRY(Secret_Club,                                                "Secret Club",                  290)
ENTRY(Praise_the_Sun,                                             "Praise the Sun",               300)
ENTRY(Fist_pump,                                                  "Fist pump",                    310)