/*
 * Dark Souls 3 - Open Server
 * Copyright (C) 2021 Tim Leonard
 *
 * This program is free software; licensed under the MIT license.
 * You should have received a copy of the license along with this program.
 * If not, see <https://opensource.org/licenses/MIT>.
 */

ENTRY(Nothing,                                                    "Nothing",                                                  -1)
ENTRY(Point_forward,                                              "Point forward",                                            0)
ENTRY(Point_up,                                                   "Point up",                                                 1)
ENTRY(point_down,                                                 "point down",                                               2)
ENTRY(Wave,                                                       "Wave",                                                     3)
ENTRY(Beckon,                                                     "Beckon",                                                   4)
ENTRY(Call_over,                                                  "Call over",                                                5)
ENTRY(Welcome,                                                    "Welcome",                                                  6)
ENTRY(Applause,                                                   "Applause",                                                 7)
ENTRY(Quiet_Resolve,                                              "Quiet Resolve",                                            8)
ENTRY(Jump_for_Joy,                                               "Jump for Joy",                                             9)
ENTRY(Joy,                                                        "Joy",                                                      10)
ENTRY(Rejoice,                                                    "Rejoice",                                                  11)
ENTRY(Hurrah,                                                     "Hurrah!",                                                  12)
ENTRY(Praise_the_Sun,                                             "Praise the Sun",                                           13)
ENTRY(My_thanks,                                                  "My thanks!",                                               14)
ENTRY(Bow,                                                        "Bow",                                                      15)
ENTRY(Proper_bow,                                                 "Proper bow",                                               16)
ENTRY(Dignified_bow,                                              "Dignified bow",                                            17)
ENTRY(Duel_bow,                                                   "Duel bow",                                                 18)
ENTRY(Legion_Etiquette,                                           "Legion Etiquette",                                         19)
ENTRY(Darkmoon_Loyality,                                          "Darkmoon Loyality",                                        20)
ENTRY(By_my_sword,                                                "By my sword",                                              21)
ENTRY(Prayer,                                                     "Prayer",                                                   22)
ENTRY(Silent_Ally,                                                "Silent Ally",                                              23)
ENTRY(Rest,                                                       "Rest",                                                     24)
ENTRY(Collapse,                                                   "Collapse",                                                 25)
ENTRY(Patches_Squat,                                              "Patches Squat",                                            26)
ENTRY(Prostration,                                                "Prostration",                                              27)
ENTRY(Toast,                                                      "Toast",                                                    28)
ENTRY(Sleep,                                                      "Sleep",                                                    29)
ENTRY(Curl_up,                                                    "Curl up",                                                  30)
ENTRY(Stretch_out,                                                "Stretch out",                                              31)
ENTRY(Patch_of_the_Dragon,                                        "Patch of the Dragon",                                      32)
ENTRY(Unmannered_bow,                                             "Unmannered bow",                                           33)
ENTRY(Lord_of_Cinder,                                             "Lord of Cinder",                                           34)