/*
 * Dark Souls 3 - Open Server
 * Copyright (C) 2021 Tim Leonard
 *
 * This program is free software; licensed under the MIT license.
 * You should have received a copy of the license along with this program.
 * If not, see <https://opensource.org/licenses/MIT>.
 */

ENTRY(Empty,                                                      "Empty",                                                    -1)

/*

03B2F5E0:Cracked Red Eye Orb
03B2CED0:Cracked Blue Eye Orb
03B2BB48:Red Sign Soapstone
03B20B80:Dried Fingers
03B259A0:Bone of Order
03B280B0:White Sign Soapstone
03B2A7C0:Small White Sign Soapstone
03B31CF0:Dragon Eye
03B39220:Token of Fidelity
03B3B930:Token of Spite
03B3E040:Sunlight Medal
03B40750:Dragon Scale
03B42E60:Rat Tail
03B45570:Awestone
0395D4D8:Human Effigy
000F4240:Dagger
000F6950:Bandit's Knife
000FDE80:Mytha's Bent Blade
00100590:Shadow Dagger
00102CA0:Thief Dagger
001053B0:Broken Thief Sword
0010C8E0:Parrying Dagger
0010EFF0:Manikin Knife
00113E10:Royal Dirk
00116520:Blue Dagger
00118C30:Umbral Dagger
0011B340:Retainer's Short Sword
00124F80:Broken Straight Sword
00127690:Shortsword
00129DA0:Longsword
0012C4B0:Broadsword
0012EBC0:Foot Soldier Sword
001312D0:Puzzling Stone Sword
001339E0:Possessed Armor Sword
001360F0:Varangian Sword
00138800:Blue Flame
0013AF10:Fume Sword
00142440:Heide Knight Sword
00144B50:Red Rust Sword
00147260:no text
00149970:Black Dragon Sword
0014C080:Sun Sword
0014E790:Drakekeeper's Sword
00150EA0:Ashen Warrior Sword
001535B0:Ivory Straight Sword
00155CC0:Estoc
001583D0:Mail Breaker
0015AAE0:Chaos Rapier
0015D1F0:Spider's Silk
0015F900:Espada Ropera
0016E360:Rapier
00173180:Black Scorpion Stinger
00175890:Ricard's Rapier
00181BE0:Ice Rapier
00186A00:Falchion
00189110:Shotel
0018B820:Warped Sword
0018DF30:Eleum Loyce
00190640:Manikin Sabre
00192D50:Scimitar
00195460:Red Rust Scimitar
00197B70:Spider Fang
0019A280:Melu Scimitar
0019C990:Monastery Scimitar
0019F0A0:Uchigatana
001A17B0:Washing Pole
001A3EC0:Chaos Blade
001A65D0:Blacksteel Katana
001A8CE0:Manslayer
001ADB00:Darkdrift
001B0210:Berserker Blade
001B5030:Bewitched Alonne Sword
001B7740:Bastard Sword
001B9E50:Flamberge
001BC560:Claymore
001BEC70:Majestic Greatsword
001BF058:Majestic Greatsword
001C3A90:Drangleic Sword
001C61A0:Thorned Greatsword
001C88B0:Bluemoon Greatsword
001C8C98:Moonlight Greatsword
001CAFC0:Mastodon Greatsword
001CFDE0:Ruler's Sword
001D24F0:Mirrah Greatsword
001D28D8:Old Mirrah Greatsword
001D4C00:Black Dragon Greatsword
001D7310:Black Knight Greatsword
001D9A20:Royal Greatsword
001DC130:Old Knight Greatsword
001DE840:Defender Greatsword
001E0F50:Watcher Greatsword
001E3660:Key to the Embedded
001E5D70:Drakeblood Greatsword
001E70F8:Loyce Greatsword
001E74E0:Charred Loyce Greatsword
001E8480:Hand Axe
001EAB90:Battle Axe
001ED2A0:Bandit Axe
001EF9B0:Infantry Axe
001F95F0:Gyrm Axe
001FBD00:Dragonslayer's Crescent Axe
001FE410:Butcher's Knife
00200B20:Silverblack Sickle
002191C0:Crescent Axe
0021B8D0:Greataxe
0021DFE0:Bandit Greataxe
00222E00:Lion Greataxe
00225510:Giant Stone Axe
00227C20:Gyrm Greataxe
0022F150:Black Dragon Greataxe
00231860:Black Knight Greataxe
00233F70:Drakekeeper's Greataxe
00249F00:Club
0024C610:Mace
0024ED20:Morning Star
00251430:Reinforced Club
00253B40:Craftsman's Hammer
0025B070:Mace of the Insolent
002625A0:Handmaid's Ladle
002673C0:Blacksmith's Hammer
00269AD0:Black Dragon Warpick
0026C1E0:Aldia Hammer
00271000:Barbed Club
0027AC40:Large Club
0027D350:Pickaxe
0027FA60:Great Club
00282170:Gyrm Great Hammer
002896A0:Iron King Hammer
0028BDB0:Malformed Skull
0028E4C0:Dragon Tooth
00290BD0:Giant Warrior Club
002932E0:Malformed Shell
002959F0:Demon's Great Hammer
00298100:Archdrake Mace
0029A810:Old Knight Hammer
0029CF20:Drakekeeper's Great Hammer
0029F630:Sacred Chime Hammer
002A1D40:Sanctum Mace
002AB980:Spear
002AE090:Winged Spear
002B07A0:Pike
002B2EB0:Partizan
002B55C0:Stone Soldier Spear
002B7CD0:Spitfire Spear
002B9058:Yorgh's Spear
002BA3E0:Silverblack Spear
002BCAF0:Heide Spear
002BF200:Pate's Spear
002C1910:Channeler's Trident
002C2C98:Gargoyle Bident
002C3080:Dragonslayer Spear
002C4020:Heide Lance
002C8E40:Heide Greatlance
002CB550:Grand Lance
002CDC60:Chariot Lance
002D0370:Rampart Golem Lance
002D2A80:Smelter Hammer
002DC6C0:Great Scythe
002DEDD0:Great Machete
002E14E0:Full Moon Sickle
002E6300:Crescent Sickle
002E8A10:Scythe of Nahr Alma
002EB120:Bone Scythe
002ED830:Scythe of Want
0030D400:Lucerne
0030FB10:Scythe
00312220:Halberd
00317040:Helix Halberd
00319750:Santier's Spear
00319B38:Santier's Spear
0031E570:Mastodon Halberd
00320C80:Blue Knight's Halberd
00323390:Dragonrider's Halberd
00325AA0:Black Knight Halberd
003281B0:Syan's Halberd
0032A8C0:Roaring Halberd
0032CFD0:Old Knight Halberd
0032F6E0:Old Knight Pike
00331DF0:Drakekeeper's Warpick
00336C10:Wrathful Axe
00340850:Claws
00342F60:Malformed Claws
00345670:Manikin Claws
00347D80:Work Hook
003567E0:Caestus
00358EF0:Shadow Claws
0035DD10:Bone Fist
0036EE80:Whip
00371590:Notched Whip
00373CA0:Bloodied Whip
003763B0:Spotted Whip
0037D8E0:Old Whip
0039FBC0:Sorcerer's Staff
003A22D0:Staff of Amana
003A49E0:Witchtree Branch
003A70F0:Lizard Staff
003ABF10:Olenford's Staff
003AE620:Archdrake Staff
003B0D30:Bat Staff
003B3440:Bone Staff
003B5B50:Staff of Wisdom
003B8260:Sunset Staff
003BA970:Pilgrim's Spontoon
003BF790:Azal's Staff
003C1EA0:Retainer Staff
003D3010:Cleric's Sacred Chime
003D5720:Witchtree Bellvine
003D7E30:Priest's Chime
003DA540:Dragon Chime
003DCC50:Chime of Want
003DF360:Archdrake Chime
003E4180:Idol's Chime
003E6890:Caitha's Chime
003E8FA0:Protective Chime
003EB6B0:Disc Chime
003EDDC0:Chime of Screams
003F52F0:Black Witch's Staff
00401640:Short Bow
00403D50:Long Bow
00406460:Composite Bow
00408B70:Sea Bow
0040B280:Dragonrider Bow
004127B0:Bell Keeper Bow
00414EC0:Bow of Want
004175D0:Hunter's Blackbow
00432380:Alonne Greatbow
004371A0:Dragonslayer Greatbow
004398B0:Possessed Armor Greatbow
0043BFC0:Twin-headed Greatbow
004630C0:Light Crossbow
004657D0:Heavy Crossbow
0046A5F0:Shield Crossbow
00471B20:Avelyn
00474230:Sanctum Crossbow
00476940:Sanctum Repeating Crossbow
004C4B40:Murakumo
004C7250:Arced Sword
004CE780:Curved Dragon Greatsword
004D0E90:Curved Nil Greatsword
004F5880:Zweihander
004F7F90:Greatsword
004FA6A0:Smelter Sword
004FBA28:Aged Smelter Sword
004FCDB0:Drakewing Ultra Greatsword
004FF4C0:King's Ultra Greatsword
00501BD0:Fume Ultra Greatsword
00502F58:Ivory King Ultra Greatsword
005069F0:Pursuer's Ultra Greatsword
00507D78:Drakekeeper's Ultra Greatsword
00509100:Crypt Blacksword
0050A488:Old Knight Ultra Greatsword
0050B810:Black Knight Ultra Greatsword
0050CB98:Lost Sinner's Sword
00510630:Stone Twinblade
00515450:Dragonrider Twinblade
00517B60:Twinblade
0051A270:Red Iron Twinblade
0051C980:Curved Twinblade
0051F090:Sorcerer's Twinblade
005265C0:Pyromancy Flame
00528CD0:Dark Pyromancy Flame
0053EC60:Black Flamestone Dagger
00541370:Yellow Quartz Longsword
00543A80:Bound Hand Axe
00546190:Homunculus Mace
005488A0:Transgressor's Staff
00557300:Longsword
00559A10:Murakumo
0055C120:Blacksteel Katana
0055E830:Rapier
00560F40:Greataxe
00563650:Great Club
00565D60:Caestus
005D1420:Binoculars
00A7D8C0:Buckler
00A7EC48:Benhart's Parma
00A7FFD0:Small Leather Shield
00A826E0:Iron Parma
00A84DF0:Foot Soldier Shield
00A87500:Target Shield
00A89C10:Golden Falcon Shield
00A8EA30:Manikin Shield
00A91140:Llewellyn Shield
00A93C38:Crimson Parma
00A98670:Cleric's Parma
00A9AD80:Cleric's Small Shield
00A9D490:Magic Shield
00A9FBA0:Cursed Bone Shield
00AA22B0:Sanctum Shield
00AA49C0:Varangian Shield
00AAAB68:Watcher's Shield
00AAE600:Large Leather Shield
00AB0D10:Blue Wooden Shield
00AB3420:Silver Eagle Kite Shield
00AB5B30:Drangleic Shield
00AB8240:Lion Clan Shield
00ABA950:Archdrake Shield
00ABD060:King's Shield
00ABF770:Mirrah Shield
00AC1E80:Old Knight's Shield
00AC4590:Loyce Shield
00AC5918:Charred Loyce Shield
00AC6CA0:Spirit Tree Shield
00AC93B0:Golden Wing Shield
00ACBAC0:Vessel Shield
00ACE1D0:Shield of the Insolent
00AD2FF0:Silverblack Shield
00AD5700:Stone Parma
00AD7E10:Grand Spirit Tree Shield
00ADA520:Moon Butterfly Shield
00ADCC30:Slumbering Dragon Shield
00ADDFB8:Chaos Shield
00ADF340:Wooden Shield
00AE4160:Hollow Soldier Shield
00AE6870:Royal Kite Shield
00AEB690:Red Rust Shield
00AECA18:Rampart Golem Shield
00AF04B0:Bell Keeper Shield
00AF1838:Defender's Shield
00AF2BC0:Black Dragon Shield
00AF3F48:Drakekeeper's Shield
00AF52D0:Porcine Shield
00AF6658:Bone Shield
00AF79E0:Twin Dragon Greatshield
00AFA0F0:Tower Shield
00AFEF10:Orma's Greatshield
00B01620:Reeve's Greatshield
00B03D30:King's Mirror
00B06440:Dragonrider Greatshield
00B08B50:Mastodon Greatshield
00B0D970:Havel's Greatshield
00B10080:Gyrm Greatshield
00B12790:Pursuer's Greatshield
00B14EA0:Pate's Shield
00B175B0:Old Knight Greatshield
00B19CC0:Drakekeeper's Greatshield
00B1C3D0:Greatshield of Glory
00B28720:Phoenix Parma
00B2AE30:Sunlight Parma
00B2D540:Watchdragon Parma
00B2FC50:Blossom Kite Shield
00B32360:Rebel's Greatshield
00B34A70:Wicked Eye Greatshield
00B40DC0:Black Flamestone Parma
00B434D0:Yellow Quartz Shield
00B45BE0:Bound Wooden Shield
00B482F0:Homunculus Wooden Shield
00B4AA00:Transgressor's Leather Shield
014096B4:Pate's Helm
014096B5:Pate's Armor
014096B6:Pate's Gloves
014096B7:Pate's Trousers
0140BDC4:Thief Mask
0140BDC5:Black Leather Armor
0140BDC6:Black Leather Gloves
0140BDC7:Black Leather Boots
0140E4D4:Wanderer Hood
0140E4D5:Wanderer Coat
0140E4D6:Wanderer Manchettes
0140E4D7:Wanderer Boots
01410BE4:Hunter's Hat
01410BE5:Leather Armor
01410BE6:Leather Gloves
01410BE7:Leather Boots
01410FCC:Hunter's Hat
014132F4:Knight Helm
014132F5:Knight Armor
014132F6:Knight Gauntlets
014132F7:Knight Leggings
01415A04:Elite Knight Helm
01415A05:Elite Knight Armor
01415A06:Elite Knight Gloves
01415A07:Elite Knight Leggings
01418114:Tattered Cloth Hood
01418115:Tattered Cloth Robe
01418116:Tattered Cloth Manchettes
01418117:Heavy Boots
0141A824:Brigand Hood
0141A825:Brigand Armor
0141A826:Brigand Gauntlets
0141A827:Brigand Trousers
0141F644:Imported Hood
0141F645:Imported Tunic
0141F646:Imported Manchettes
0141F647:Imported Trousers
01429284:Traveling Merchant Hat
01429285:Traveling Merchant Coat
01429286:Traveling Merchant Gloves
01429287:Traveling Merchant Boots
0142E0A4:Havel's Helm
0142E0A5:Havel's Armor
0142E0A6:Havel's Gauntlets
0142E0A7:Havel's Leggings
0143A3F4:Jester's Cap
0143A3F5:Jester's Robes
0143A3F6:Jester's Gloves
0143A3F7:Jester's Tights
0143F214:Moon Hat
0143F215:Astrologist's Robe
0143F216:Astrologist's Gauntlets
0143F217:Astrologist's Bottoms
014551A4:Faraam Helm
014551A5:Faraam Armor
014551A6:Faraam Gauntlets
014551A7:Faraam Boots
014578B4:Black Dragon Helm
014578B5:Black Dragon Armor
014578B6:Black Dragon Gauntlets
014578B7:Black Dragon Leggings
01459FC4:Xanthous Crown
01459FC5:Xanthous Overcoat
01459FC6:Xanthous Gloves
01459FC7:Xanthous Waistcloth
0145C6D4:Mask of Judgment
0145C6D5:Robe of Judgment
0145C6D6:Manchettes of Judgment
0145C6D7:Tights of Judgment
0145EDE4:Helm of Aurous
0145EDE5:Armor of Aurous
0145EDE6:Gauntlets of Aurous
0145EDE7:Leggings of Aurous
0145F1CC:Helm of Aurous
0145F1CD:Armor of Aurous
0145F1CE:Gauntlets of Aurous
0145F1CF:Leggings of Aurous
014614F4:Monastery Headcloth
014614F5:Monastery Longshirt
014614F6:Monastery Long Gloves
014614F7:Monastery Skirt
01466314:Dingy Hood
01466315:Dingy Robe
01466316:Dingy Cuffs
01466317:Blood-Stained Skirt
0146FF54:Durgo's Hat
01472666:Engraved Gauntlets
01474D75:Barrel
01477487:Flying Feline Boots
01479B94:Moon Butterfly Hat
01479B95:Moon Butterfly Wings
01479B96:Moon Butterfly Cuffs
01479B97:Moon Butterfly Skirt
0147C2A4:Catarina Helm
0147C2A5:Catarina Armor
0147C2A6:Catarina Gauntlets
0147C2A7:Catarina Leggings
0147E9B4:Alva Helm
0147E9B5:Alva Armor
0147E9B6:Alva Gauntlets
0147E9B7:Alva Leggings
014810C4:Black Witch Veil
014810C5:Black Witch Robe
014810C6:Black Witch Gloves
014810C7:Black Witch Trousers
014814AC:Black Witch Hat
01481894:Black Witch Domino Mask
01499764:Drakeblood Helm
01499765:Drakeblood Armor
01499766:Drakeblood Gauntlets
01499767:Drakeblood Leggings
0149BE74:Northwarder Hood
0149BE75:Northwarder Robe
0149BE76:Northwarder Manchettes
0149BE77:Northwarder Trousers
014A0C94:Crown of the Old Iron King
014A33A4:Crown of the Ivory King
014A5AB4:Crown of the Sunken King
014A81C4:Old Bell Helm
014AA8D4:Hollow Skin
014ACFE4:Pharros Mask
014AF6F7:Flower Skirt
014B1E04:Minotaur Helm
014B4514:Symbol of Avarice
01500004:Hollow Soldier Helm
01500005:Hollow Soldier Armor
01500006:Hollow Soldier Gauntlets
01500007:Hollow Soldier Leggings
015003EC:Royal Soldier Helm
015003ED:Royal Soldier Armor
015003EE:Royal Soldier Gauntlets
015003EF:Royal Soldier Leggings
01502714:Hollow Infantry Helm
01502715:Hollow Infantry Armor
01502716:Hollow Infantry Gloves
01502717:Hollow Infantry Boots
01502AFC:Infantry Helm
01502AFD:Infantry Armor
01502AFE:Infantry Gloves
01502AFF:Infantry Boots
01509C44:White Priest Headpiece
01509C45:White Priest Robe
01509C46:White Priest Gloves
01509C47:White Priest Skirt
0150A414:Priestess Headpiece
0150A415:Priestess Robe
0150A416:Priestess Gloves
0150A417:Priestess Skirt
0150EA64:Rogue Hood
0150EA65:Rogue Armor
0150EA66:Rogue Gauntlets
0150EA67:Rogue Leggings
01515F94:Spiked Bandit Helm
01515F95:Bandit Armor
01515F96:Bandit Gauntlets
01515F97:Bandit Boots
0151ADB4:Varangian Helm
0151ADB5:Varangian Armor
0151ADB6:Varangian Cuffs
0151ADB7:Varangian Leggings
01527104:Black Hollow Mage Hood
01527105:Black Hollow Mage Robe
015278D4:White Hollow Mage Hood
015278D5:White Hollow Mage Robe
01529815:Lion Mage Robe
01529816:Lion Mage Cuffs
01529817:Lion Mage Skirt
01530D44:Steel Helm
01530D45:Steel Armor
01530D46:Steel Gauntlets
01530D47:Steel Leggings
01533454:Shadow Mask
01533455:Shadow Top
01533456:Shadow Gauntlets
01533457:Shadow Leggings
01535B64:Manikin Mask
01535B65:Manikin Top
01535B66:Manikin Gloves
01535B67:Manikin Boots
0153D094:Prisoner's Hood
0153D095:Prisoner's Tatters
0153D096:Prisoner's Gloves
0153D097:Prisoner's Waistcloth
0153D47C:Prisoner's Hood
0153D47D:Prisoner's Tatters
01546CD4:Archdrake Helm
01546CD5:Archdrake Robes
01546CD6:Archdrake Gloves
01546CD7:Archdrake Boots
0154E204:Gyrm Helm
0154E205:Gyrm Armor
0154E206:Gyrm Gloves
0154E207:Gyrm Boots
01550914:Gyrm Warrior Helm
01550915:Gyrm Warrior Armor
01550916:Gyrm Warrior Gloves
01550917:Gyrm Warrior Boots
01550CFC:Gyrm Warrior Greathelm
01553024:Dark Mask
01553025:Dark Armor
01553026:Dark Gauntlets
01553027:Dark Leggings
01555734:Warlock Mask
0156B6C4:Tseldora Cap
0156B6C5:Tseldora Robe
0156B6C6:Tseldora Manchettes
0156B6C7:Tseldora Trousers
015704E4:Peasant Hat
015704E5:Peasant Attire
015704E6:Peasant Long Gloves
015704E7:Peasant Trousers
01577A14:Ironclad Helm
01577A15:Ironclad Armor
01577A16:Ironclad Gauntlets
01577A17:Ironclad Leggings
015781E4:Old Ironclad Helm
015781E5:Old Ironclad Armor
015781E6:Old Ironclad Gauntlets
015781E7:Old Ironclad Leggings
0157A124:Royal Swordsman Helm
0157A125:Royal Swordsman Armor
0157A126:Royal Swordsman Gloves
0157A127:Royal Swordsman Leggings
0157C834:Syan's Helm
0157C835:Syan's Armor
0157C836:Syan's Gauntlets
0157C837:Syan's Leggings
0157EF44:Bone Crown
0157EF45:Bone King Robe
0157EF46:Bone King Cuffs
0157EF47:Bone King Skirt
015F1B34:Heide Knight Greathelm
015F1B35:Heide Knight Chainmail
015F1B36:Heide Knight Gauntlets
015F1B37:Heide Knight Leggings
015F1F1C:Heide Knight Iron Mask
015F9065:Singer's Dress
015F944D:Singer's Dress
015F9835:Singer's Dress
015FB774:Smelter Demon Helm
015FB775:Smelter Demon Armor
015FB776:Smelter Demon Gauntlets
015FB777:Smelter Demon Leggings
015FDE84:Alonne Captain Helm
015FDE85:Alonne Captain Armor
015FE26C:Alonne Knight Helm
015FE26D:Alonne Knight Armor
015FE26E:Alonne Knight Gauntlets
015FE26F:Alonne Knight Leggings
01600594:Vengarl's Helm
01600595:Vengarl's Armor
01600596:Vengarl's Gloves
01600597:Vengarl's Boots
01602CA5:Lion Warrior Cape
01602CA6:Lion Warrior Cuffs
01602CA7:Lion Warrior Skirt
0160308C:Lion Warrior Helm
0160308D:Red Lion Warrior Cape
0160C8E4:Grave Warden Mask
0160C8E5:Grave Warden Top
0160C8E6:Grave Warden Cuffs
0160C8E7:Grave Warden Bottoms
0160EFF4:Falconer Helm
0160EFF5:Falconer Armor
0160EFF6:Falconer Gloves
0160EFF7:Falconer Boots
01611704:Rusted Mastodon Helm
01611705:Rusted Mastodon Armor
01611706:Rusted Mastodon Gauntlets
01611707:Rusted Mastodon Leggings
01613E14:Mastodon Helm
01613E15:Mastodon Armor
01613E16:Mastodon Gauntlets
01613E17:Mastodon Leggings
01616524:Desert Sorceress Hood
01616525:Desert Sorceress Top
01616526:Desert Sorceress Gloves
01616527:Desert Sorceress Skirt
01618C34:Dragon Acolyte Mask
01618C35:Dragon Acolyte Robe
01618C36:Dragon Acolyte Gloves
01618C37:Dragon Acolyte Boots
0161901C:Dragon Sage Hood
0162C4B4:Ruin Helm
0162C4B5:Ruin Armor
0162C4B6:Ruin Gauntlets
0162C4B7:Ruin Leggings
01638804:Old Knight Helm
01638805:Old Knight Armor
01638806:Old Knight Gauntlets
01638807:Old Knight Leggings
0163AF14:Drakekeeper Helm
0163AF15:Drakekeeper Armor
0163AF16:Drakekeeper Gauntlets
0163AF17:Drakekeeper Boots
0163D624:Throne Defender Helm
0163D625:Throne Defender Armor
0163D626:Throne Defender Gauntlets
0163D627:Throne Defender Leggings
0163FD34:Velstadt's Helm
0163FD35:Velstadt's Armor
0163FD36:Velstadt's Gauntlets
0163FD37:Velstadt's Leggings
01642444:Throne Watcher Helm
01642445:Throne Watcher Armor
01642446:Throne Watcher Gauntlets
01642447:Throne Watcher Leggings
017E14E4:Looking Glass Mask
017E14E5:Looking Glass Armor
017E14E6:Looking Glass Gauntlets
017E14E7:Looking Glass Leggings
017E6305:Agdayne's Black Robe
017E6306:Agdayne's Cuffs
017E6307:Agdayne's Kilt
017ED834:Leydia Black Hood
017ED835:Leydia Black Robe
017EFF44:Insolent Helm
017EFF45:Insolent Armor
017EFF46:Insolent Gloves
017EFF47:Insolent Boots
017F2654:Imperious Helm
017F2655:Imperious Armor
017F2656:Imperious Gloves
017F2657:Imperious Leggings
017F4D64:Leydia White Hood
017F4D65:Leydia White Robe
017F4D66:Leydia Gauntlets
017F7474:King's Crown
017F7475:King's Armor
017F7476:King's Gauntlets
017F7477:King's Leggings
018E4184:Dragonrider Helm
018E4185:Dragonrider Armor
018E4186:Dragonrider Gauntlets
018E4187:Dragonrider Leggings
018F7A04:Executioner Helm
018F7A05:Executioner Armor
018F7A06:Executioner Gauntlets
018F7A07:Executioner Leggings
0190B284:Penal Mask
0190B285:Penal Straightjacket
0190B286:Penal Handcuffs
0190B287:Penal Skirt
01948314:Fume Sorcerer Mask
01948315:Fume Sorcerer Robes
01948316:Fume Sorcerer Gloves
01948317:Fume Sorcerer Boots
0195BB94:Rampart Golem Helm
0195BB95:Rampart Golem Armor
0195BB96:Rampart Golem Gauntlets
0195BB97:Rampart Golem Leggings
0196A5F4:Sanctum Knight Helm
0196A5F5:Sanctum Knight Armor
0196A5F6:Sanctum Knight Gauntlets
0196A5F7:Sanctum Knight Leggings
0196CD06:Sanctum Soldier Gauntlet
01976944:Sanctum Priestess Tiara
01982C94:Raime's Helm
01982C95:Raime's Armor
01982C96:Raime's Gauntlets
01982C97:Raime's Leggings
01987AB5:Retainer Robe
0198EFE4:Alonne's Helm
0198EFE5:Alonne's Armor
0198EFE6:Alonne's Gauntlets
0198EFE7:Alonne's Leggings
019A2864:Loyce Helm
019A2865:Loyce Armor
019A2866:Loyce Gauntlets
019A2867:Loyce Leggings
019A4F74:Charred Loyce Helm
019A4F75:Charred Loyce Armor
019A4F76:Charred Loyce Gauntlets
019A4F77:Charred Loyce Leggings
019A7684:Ivory King Helm
019A7685:Ivory King Armor
019A7686:Ivory King Gauntlets
019A7687:Ivory King Leggings
019F3175:Llewellyn Armor
019F3176:Llewellyn Gloves
019F3177:Llewellyn Shoes
019FA6A4:Drangleic Helm
019FA6A5:Drangleic Mail
019FA6A6:Drangleic Gauntlets
019FA6A7:Drangleic Leggings
01A265C4:Creighton's Steel Mask
01A265C5:Creighton's Chainmail
01A265C6:Creighton's Chain Gloves
01A265C7:Creighton's Chain Leggings
01A28CD4:Benhart's Knight Helm
01A28CD5:Benhart's Armor
01A28CD6:Benhart's Gauntlets
01A28CD7:Benhart's Boots
01A2B3E4:Standard Helm
01A2B3E5:Hard Leather Armor
01A2B3E6:Hard Leather Gauntlets
01A2B3E7:Hard Leather Boots
01A3C554:Cale's Helm
01A3C555:Cale's Leather Armor
01A3C557:Cale's Shoes
01A3EC64:Lucatiel's Mask
01A3EC65:Lucatiel's Vest
01A3EC66:Lucatiel's Gloves
01A3EC67:Lucatiel's Trousers
01A3F04C:Mirrah Hat
01A41374:Bell Keeper Helmet
01A41375:Bell Keeper Bellyband
01A41376:Bell Keeper Cuffs
01A41377:Bell Keeper Trousers
01A46194:Mad Warrior Mask
01A46195:Mad Warrior Armor
01A46196:Mad Warrior Gauntlets
01A46197:Mad Warrior Leggings
01A59A15:Rosabeth's Dress
01A65D64:Black Hood
01A65D65:Black Robes
01A65D66:Black Gloves
01A65D67:Black Boots
01A68474:Saint's Hood
01A68475:Saint's Dress
01A68476:Saint's Long Gloves
01A68477:Saint's Trousers
01A6AB84:Hexer's Hood
01A6AB85:Hexer's Robes
01A6AB86:Hexer's Gloves
01A6AB87:Hexer's Boots
01A6D294:Chaos Hood
01A6D295:Chaos Robe
01A6D296:Chaos Gloves
01A6D297:Chaos Boots
01A8A754:Nahr Alma Hood
01A8A755:Nahr Alma Robes
01AA7C14:Targray's Helm
01AA7C15:Targray's Armor
01AA7C16:Targray's Manifers
01AA7C17:Targray's Leggings
01D92CD0:Soul Arrow
01D953E0:Great Soul Arrow
01D97AF0:Heavy Soul Arrow
01D9A200:Great Heavy Soul Arrow
01D9C910:Homing Soul Arrow
01D9F020:Heavy Homing Soul Arrow
01DA1730:Homing Soulmass
01DA3E40:Homing Crystal Soulmass
01DA6550:Soul Spear
01DA8C60:Crystal Soul Spear
01DAB370:Shockwave
01DADA80:Soul Spear Barrage
01DB0190:Soul Shower
01DB28A0:Soul Greatsword
01DB4FB0:Soul Vortex
01DB76C0:Soul Bolt
01DB9DD0:Soul Geyser
01DBC4E0:Magic Weapon
01DBEBF0:Great Magic Weapon
01DC1300:Crystal Magic Weapon
01DC3A10:Strong Magic Shield
01DC6120:Yearn
01DC8830:Hush
01DCAF40:Fall Control
01DCD650:Hidden Weapon
01DCFD60:Repair
01DD2470:Cast Light
01DD4B80:Chameleon
01DD7290:Unleash Magic
01DD99A0:Soul Flash
01DDC0B0:Focus Souls
01E86F10:Heal
01E89620:Med Heal
01E8BD30:Great Heal Excerpt
01E8E440:Great Heal
01E90B50:Soothing Sunlight
01E93260:Replenishment
01E95970:Resplendent Life
01E98080:Bountiful Sunlight
01E9A790:Caressing Prayer
01E9CEA0:Force
01E9F5B0:Wrath of the Gods
01EA1CC0:Emit Force
01EA43D0:Heavenly Thunder
01EA6AE0:Lightning Spear
01EA91F0:Great Lightning Spear
01EAB900:Sunlight Spear
01EAE010:Soul Appease
01EB0720:Blinding Bolt
01EB2E30:Magic Barrier
01EB5540:Great Magic Barrier
01EB7C50:Homeward
01EBA360:Guidance
01EBCA70:Sacred Oath
01EBF180:Unveil
01EC1890:Perseverance
01EC3FA0:Sunlight Blade
01ECDBE0:Denial
01ED02F0:Splintering Lightning Spear
01F7B150:Fireball
01F7D860:Fire Orb
01F7FF70:Great Fireball
01F82680:Great Chaos Fireball
01F84D90:Firestorm
01F874A0:Fire Tempest
01F89BB0:Chaos Storm
01F8C2C0:Combustion
01F8E9D0:Great Combustion
01F910E0:Fire Whip
01F937F0:Poison Mist
01F95F00:Toxic Mist
01F98610:Acid Surge
01F9AD20:Lingering Flame
01F9D430:Flame Swathe
01F9FB40:Forbidden Sun
01FA2250:Flame Weapon
01FA4960:Flash Sweat
01FA7070:Iron Flesh
01FA9780:Warmth
01FABE90:Immolation
01FC1E20:Fire Snake
01FC4530:Dance of Fire
01FC6C40:Outcry
0206F390:Dark Orb
02071AA0:Dark Hail
020741B0:Dark Fog
020768C0:Affinity
02078FD0:Dead Again
0207B6E0:Dark Weapon
0207DDF0:Whisper of Despair
02080500:Repel
02082C10:Twisted Barricade
02085320:Numbness
020B6060:Dark Greatsword
020B8770:Recollection
021635D0:Scraps of Life
02165CE0:Darkstorm
021683F0:Resonant Soul
0216AB00:Great Resonant Soul
0216D210:Climax
0216F920:Resonant Flesh
02172030:Resonant Weapon
02174740:Lifedrain Patch
02176E50:Profound Still
021AA2A0:Promised Walk of Peace
021AC9B0:Dark Dance
02628110:Life Ring
02628111:Life Ring+1
02628112:Life Ring+2
02628113:Life Ring+3
0262A820:Chloranthy Ring
0262A821:Chloranthy Ring+1
0262A822:Chloranthy Ring+2
0262CF30:Royal Soldier's Ring
0262CF31:Royal Soldier's Ring+1
0262CF32:Royal Soldier's Ring+2
0262F640:First Dragon Ring
0262F641:Second Dragon Ring
0262F642:Third Dragon Ring
02631D50:Ring of Steel Protection
02631D51:Ring of Steel Protection+1
02631D52:Ring of Steel Protection+2
02631D53:no text
02634460:Spell Quartz Ring
02634461:Spell Quartz Ring+1
02634462:Spell Quartz Ring+2
02634463:Spell Quartz Ring+3
02636B70:Flame Quartz Ring
02636B71:Flame Quartz Ring+1
02636B72:Flame Quartz Ring+2
02636B73:Flame Quartz Ring+3
02639280:Thunder Quartz Ring
02639281:Thunder Quartz Ring+1
02639282:Thunder Quartz Ring+2
02639283:Thunder Quartz Ring+3
0263B990:Dark Quartz Ring
0263B991:Dark Quartz Ring+1
0263B992:Dark Quartz Ring+2
0263B993:Dark Quartz Ring+3
0263E0A0:Poisonbite Ring
0263E0A1:Poisonbite Ring+1
026407B0:Bloodbite Ring
026407B1:Bloodbite Ring+1
02642EC0:Bracing Knuckle Ring
02642EC1:Bracing Knuckle Ring+1
02642EC2:Bracing Knuckle Ring+2
026455D0:Cursebite Ring
02646958:Ash Knuckle Ring
02647CE0:Dispelling Ring
02647CE1:Dispelling Ring+1
0264A3F0:Ring of Resistance
0264A3F1:Ring of Resistance+1
0264CB00:Ring of Blades
0264CB01:Ring of Blades+1
0264CB02:Ring of Blades+2
02658E50:Ring of Knowledge
0265B560:Ring of Prayer
0265DC70:Stone Ring
026651A0:Red Tearstone Ring
02669FC0:Blue Tearstone Ring
0266C6D0:Ring of Giants
0266C6D1:Ring of Giants+1
0266C6D2:Ring of Giants+2
0266DA58:Old Leo Ring
0266EDE0:Ring of Soul Protection
026714F0:Ring of Life Protection
02673C00:Lingering Dragoncrest Ring
02673C01:Lingering Dragoncrest Ring+1
02673C02:Lingering Dragoncrest Ring+2
02676310:Clear Bluestone Ring
02676311:Clear Bluestone Ring+1
02676312:Clear Bluestone Ring+2
02678A20:Northern Ritual Band
02678A21:Northern Ritual Band+1
02678A22:Northern Ritual Band+2
0267B130:Southern Ritual Band
0267B131:Southern Ritual Band+1
0267B132:Southern Ritual Band+2
0267D840:Covetous Gold Serpent Ring
0267D841:Covetous Gold Serpent Ring+1
0267D842:Covetous Gold Serpent Ring+2
0267FF50:Covetous Silver Serpent Ring
0267FF51:Covetous Silver Serpent Ring+1
0267FF52:Covetous Silver Serpent Ring+2
02684D70:Ring of the Evil Eye
02684D71:Ring of the Evil Eye+1
02684D72:Ring of the Evil Eye+2
02687480:Ring of Restoration
02689B90:Ring of Binding
0268C2A0:Silvercat Ring
0268E9B0:Redeye Ring
026910C0:Gower's Ring of Protection
026937D0:Name-engraved Ring
02695EE0:Slumbering Dragoncrest Ring
026985F0:Hawk Ring
0269AD00:Old Sun Ring
0269FB20:Illusory Ring of a Conqueror
026A2230:King's Ring
026A4940:Ring of the Dead
026A7050:Ring of Thorns
026A7051:Ring of Thorns+1
026A7052:Ring of Thorns+2
026A9760:Delicate String
026ABE70:White Ring
026AE580:Illusory Ring of the Vengeful
026B0C90:Illusory Ring of the Guilty
026BA8D0:Ring of Whispers
026BCFE0:Illusory Ring of the Exalted
026D0860:Crest of the Rat
026D2F70:Bell Keeper's Seal
026D5680:Guardian's Seal
026D7D90:Crest of Blood
026DA4A0:Blue Seal
026DCBB0:Abyss Seal
026DF2C0:Vanquisher's Seal
026E19D0:Sun Seal
026E40E0:Ancient Dragon Seal
02719C40:Simpleton's Ring
0271C350:Strength Ring
0271EA60:Dexterity Ring
02721170:Ivory Warrior Ring
02723880:Sorcery Clutch Ring
02725F90:Lightning Clutch Ring
027286A0:Fire Clutch Ring
0272ADB0:Dark Clutch Ring
0272FBD0:Baneful Bird Ring
027322E0:Flynn's Ring
027349F0:Ring of the Embedded
02737100:Ring of the Living
02739810:Yorgh's Ring
0280DE80:Agape Ring
03041840:Soldier Key
03043F50:Key to King's Passage
0304B480:Weapon Smithbox
0304DB90:Armor Smithbox
03072580:Bastille Key
03074C90:Iron Key
030773A0:Forgotten Key
03079AB0:Brightstone Key
0307C1C0:Antiquated Key
0307E8D0:Fang Key
03080FE0:House Key
030836F0:Lenigrast's Key
03085E00:Smooth &amp; Silky Stone
03087188:Small Smooth &amp; Silky Stone
03088510:Rotunda Lockstone
0308AC20:Giant's Kinship
0308D330:Ashen Mist Heart
0308FA40:Soul of a Giant
03092150:Tseldora Den Key
03094860:Champion's Tablet
03096F70:Ladder Miniature
03099680:Soul Vessel
0309BD90:Undead Lockaway Key
030A0BB0:Dull Ember
030A32C0:Crushed Eye Orb
030A59D0:Simpleton's Spice
030A80E0:Skeptic's Spice
030AA7F0:Aldia Key
03197500:Dragon Talon
031AFBA0:Heavy Iron Key
031C8240:Frozen Flower
031E08E0:Eternal Sanctum Key
031F8F80:Tower Key
03211620:Garrison Ward Key
03229CC0:no text
03236010:Dragon Stone
03242360:no text
0325AA00:no text
032730A0:no text
0328B740:no text
032A3DE0:Scorching Iron Scepter
032BC480:Smelter Wedge
032D4B20:Soul of Nadalia, Bride of Ash
032ED1C0:no text
03305860:no text
0331DF00:Eye of the Priestess
0393AE10:Lifegem
0393D520:Radiant Lifegem
0393FC30:Old Radiant Lifegem
03940FB8:Elizabeth Mushroom
039413A0:Dried Root
03942340:Amber Herb
03944A50:Twilight Herb
03947160:Wilted Dusk Herb
03949870:Poison Moss
0394E690:Monastery Charm
03950DA0:Dragon Charm
03952128:Divine Blessing
039534B0:Rouge Water
03955BC0:Crimson Water
0395E478:Estus Flask
0395E860:Estus Flask
0395F800:Small Blue Burr
03961F10:Small Yellow Burr
03964620:Small Orange Burr
03966D30:Dark Troches
03969440:Common Fruit
0396BB50:Red Leech Troches
0396E260:Yellow Sea Troches
03970970:Triclops Snake Troches
03971CF8:Old Growth Balm
039720E0:Vine Balm
039724C8:Blackweed Balm
039728B0:Goldenfruit Balm
03972C98:Brightbug
03973080:Aromatic Ooze
03974408:Pungent Ooze
03975790:Gold Pine Resin
03977EA0:Charcoal Pine Resin
0397A5B0:Dark Pine Resin
0397CCC0:Rotten Pine Resin
0397F3D0:Bleeding Serum
039841F0:Green Blossom
03986900:Rusted Coin
03989010:Rhoy's Stone
0398B720:Rhoy's Stone of Knowledge
0398DE30:Homeward Bone
0398F1B8:Aged Feather
03990540:Darksign
03992C50:Silver Talisman
03995360:Gold Talisman
03997A70:Fake Dead Talisman
0399A180:Illusory Talisman
0399B8F0:Dragon Torso Stone
0399B8FA:Dragon Torso Stone
0399C890:Repair Powder
0399EFA0:Torch
039A16B0:Flame Butterfly
039A64D0:Prism Stone
039AB2F0:Hello Carving
039ADA00:Thank You Carving
039B0110:I'm Sorry Carving
039B2820:Very Good! Carving
039B4F30:Rubbish
039B5318:Petrified Something
039B89C8:Estus Flask Shard
039B8DB0:Sublime Bone Dust
039B9198:Bonfire Ascetic
039B9D50:Alluring Skull
039BA138:Lloyd's Talisman
039BB4C0:Pharros' Lockstone
039BB8A8:Fragrant Branch of Yore
039BBC90:Fire Seed
039BC460:Throwing Knife
039BEB70:Witching Urn
039C1280:Lightning Urn
039C3990:Firebomb
039C4D18:Black Firebomb
039C60A0:Hexing Urn
039C87B0:Poison Throwing Knife
039C9B38:Dung Pie
039CAEC0:Lacerating Knife
039CD5D0:Corrosive Urn
039CFCE0:Holy Water Urn
039D1068:Fading Soul
039D23F0:Soul of a Lost Undead
039D4B00:Large Soul of a Lost Undead
039D7210:Soul of a Nameless Soldier
039D9920:Large Soul of a Nameless Soldier
039DC030:Soul of a Proud Knight
039DE740:Large Soul of a Proud Knight
039E0E50:Soul of a Brave Warrior
039E3560:Large Soul of a Brave Warrior
039E5C70:Soul of a Hero
039E8380:Soul of a Great Hero
039F1FC0:Wood Arrow
039F46D0:Iron Arrow
039F6DE0:Magic Arrow
039F94F0:Lightning Arrow
039FBC00:Fire Arrow
039FE310:Dark Arrow
03A00A20:Poison Arrow
03A03130:Lacerating Arrow
03A05840:Wooden Greatarrow
03A07F50:Iron Greatarrow
03A0A660:Magic Greatarrow
03A0CD70:Lightning Greatarrow
03A0F480:Fire Greatarrow
03A11B90:Dark Greatarrow
03A142A0:Destructive Greatarrow
03A169B0:Wood Bolt
03A190C0:Heavy Bolt
03A1B7D0:Magic Bolt
03A1DEE0:Lightning Bolt
03A205F0:Fire Bolt
03A22D00:Dark Bolt
03A25410:Titanite Shard
03A26798:Large Titanite Shard
03A27B20:Titanite Chunk
03A2A230:Titanite Slab
03A2C940:Twinkling Titanite
03A33E70:Petrified Dragon Bone
03A3B3A0:Faintstone
03A3DAB0:Boltstone
03A401C0:Firedrake Stone
03A428D0:Darknight Stone
03A44FE0:Poison Stone
03A476F0:Bleed Stone
03A4C510:Raw Stone
03A4EC20:Magic Stone
03A51330:Old Mundane Stone
03A53A40:Palestone
03B47C80:Black Separation Crystal
03B4A390:Seed of a Tree of Giants
03B4F1B0:Petrified Egg
03C14DC0:"Point" Gesture
03C151A8:"I won't bite" Gesture
03C15590:"Proper bow" Gesture
03C15978:"Bow" Gesture
03C15D60:"Welcome" Gesture
03C16148:"Duel bow" Gesture
03C16530:"Wave" Gesture
03C16918:"Pumped up" Gesture
03C16D00:"Joy" Gesture
03C170E8:"Warcry" Gesture
03C174D0:"Warmup" Gesture
03C178B8:"Hurrah!" Gesture
03C17CA0:"Righty-ho!" Gesture
03C18088:"No way" Gesture
03C18470:"This one's me" Gesture
03C18858:"Have mercy!" Gesture
03C18C40:"Prostration" Gesture
03C19028:"Decapitate" Gesture
03C19410:"Fist pump" Gesture
03C197F8:"Mock" Gesture
03C19FC8:"Praise the Sun" Gesture
03D09000:Soul of the Pursuer
03D0B710:Soul of the Last Giant
03D0DE20:Dragonrider Soul
03D10530:Old Dragonslayer Soul
03D12C40:Flexile Sentry Soul
03D15350:Ruin Sentinel Soul
03D17A60:Soul of the Lost Sinner
03D1A170:Executioner's Chariot Soul
03D1C880:Skeleton Lord's Soul
03D1EF90:Covetous Demon Soul
03D216A0:Mytha, the Baneful Queen Soul
03D23DB0:Smelter Demon Soul
03D264C0:Old Iron King Soul
03D28BD0:Royal Rat Vanguard Soul
03D2B2E0:Soul of the Rotten
03D2D9F0:Scorpioness Najka Soul
03D30100:Royal Rat Authority Soul
03D32810:Soul of the Duke's Dear Freja
03D34F20:Looking Glass Knight Soul
03D37630:Demon of Song Soul
03D39D40:Soul of Velstadt
03D3C450:Soul of the King
03D3EB60:Guardian Dragon Soul
03D41270:Ancient Dragon Soul
03D43980:Giant Lord Soul
03D46090:Soul of Nashandra
03D487A0:Throne Defender Soul
03D4AEB0:Throne Watcher Soul
03D4D5C0:Darklurker Soul
03D4FCD0:Belfry Gargoyle Soul
03D523E0:Old Witch Soul
03D54AF0:Old King Soul
03D57200:Old Dead One Soul
03D59910:Old Paledrake Soul
03D83120:Soul of Sinh, the Slumbering Dragon
03D85830:Soul of the Fume Knight
03D87F40:Soul of Aava, the King's Pet
03D8A650:Soul of Elana, Squalid Queen
03D8CD60:Soul of Nadalia, Bride of Ash
03D8F470:Soul of Alsanna, Silent Oracle
03D91B80:Soul of Sir Alonne
03D969A0:Soul of the Ivory King
03D990B0:Soul of Zallen, the King's Pet
03D9B7C0:Loyce Soul
03D9DED0:Soul of Lud, the King's Pet
352ADAE8:Faraam Helm
352ADAE9:Faraam Armor
352ADAEA:Faraam Gauntlets
352ADAEB:Faraam Boots
352ADB4C:Chaos Hood
352ADB4D:Chaos Robes
352ADB4E:Chaos Gloves
352ADB4F:Chaos Boots
352ADBB0:Dragonknight Helm
352ADBB1:Dragonknight Robes
352ADBB2:Dragonknight Gloves
352ADBB3:Dragonknight Boots
352ADC14:Black Hood
352ADC15:Black Robes
352ADC16:Black Gloves
352ADC17:Black Boots
352ADC78:Hunter's Hat
352ADC79:Leather Armor
352ADC7A:Leather Gloves
352ADC7B:Leather Boots
352ADCDC:Knight Helm
352ADCDD:Knight Armor
352ADCDE:Knight Gauntlets
352ADCDF:Knight Leggings
352ADD40:Rogue Hood
352ADD41:Rogue Armor
352ADD42:Rogue Gauntlets
352ADD43:Rogue Leggings
352ADDA4:Prisoner's Hood
352ADDA5:Prisoner's Tatters
352ADDA6:Prisoner's Gloves
352ADDA7:Prisoner's Waistcloth
352ADE08:Prisoner's Hood
352ADE09:Prisoner's Tatters
352ADE0A:Prisoner's Gloves
352ADE0B:Prisoner's Waistcloth
352ADE6C:Hollow Mage Hood
352ADE6D:Hollow Mage Robes
352ADED0:Defender Helm
352ADED1:Defender Mail
352ADED2:Defender's Gauntlet
352ADED3:Defender's Leggings
352ADF35:Llewellyn Armor
352ADF36:Llewellyn Gloves
352ADF37:Llewellyn Shoes
352ADF98:Despatcher's Hood
352ADF99:Despatcher's Robes
35A509D0:Dagger
35A509D1:Royal Dirk
35A509D2:Longsword
35A509D3:Shortsword
35A509D4:Dragonslayer's Crescent Axe
35A509D5:Greataxe
35A509D6:Dragonrider's Halberd
35A509D7:Witchtree Branch
35A509D8:Lizard Staff
35A509D9:Dragonknight's Bell
35A509DA:Bell of the Idol
35A509DB:Short Bow
35A509DC:Light Crossbow
35A509DD:Target Shield
35A509DE:Small Leather Shield
35A509DF:Golden Wing Shield
35A509E0:Dragonknight's Shield
35A509E1:Silver Eagle Kite Shield
35A509E2:Imperial Shield
35A509E3:Disc Bell
35A509E4:Pursuer's Greatsword
35A509E5:Zweihander
35A509E6:Winged Spear
35A509E7:Estoc
35A509E8:Bastard Sword
35A509E9:Knight's Greatsword
35A509EA:Inquisitor's Blade
019B12C4:Forlorn Helm
019B12C5:Forlorn Armor
019B12C6:Forlorn Gauntlets
019B12C7:Forlorn Leggings
001E78C8:Greatsword of the Forlorn
002EFF40:Scythe of the Forlorn

*/