/*
 * Dark Souls 3 - Open Server
 * Copyright (C) 2021 Tim Leonard
 *
 * This program is free software; licensed under the MIT license.
 * You should have received a copy of the license along with this program.
 * If not, see <https://opensource.org/licenses/MIT>.
 */

ENTRY(None, "None", 0)
ENTRY(Things_Betwixt, "Things Betwixt", 0x0098e4a0)
ENTRY(Majula, "Majula", 0x009932c0)
ENTRY(Forest_of_Fallen_Giants, "Forest of Fallen Giants", 0x009a1d20)
ENTRY(Heides_Tower_of_Flame, "Heide's Tower of Flame", 0x009d5170)
ENTRY(Path_To_No_Mans_Wharf, "Path to No-man's Wharf", 0x009d2a60)
ENTRY(No_Mans_Wharf, "No-man's Wharf", 0x009b55a0)
ENTRY(The_Lost_Bastille, "The Lost Bastille", 0x009b0780)
ENTRY(Sinners_Rise, "Sinner's Rise", 0x009b0780)
ENTRY(Huntsmans_Copse, "Huntsman's Copse", 0x009c18f0)
ENTRY(Harvest_Valley, "Harvest Valley", 0x009b2e90)
ENTRY(Iron_Keep, "Iron Keep", 0x009b7cb0)
ENTRY(Shaded_Woods, "Shaded Woods", 0x009d0350)
ENTRY(Shaded_Woods_Fork, "Ruined Fork Road", 0x009d7880)
ENTRY(Doors_of_Pharros, "Doors of Pharros", 0x009d9f90)
ENTRY(Brightstone_Cove_Tseldora, "Brightstone Cove Tseldora", 0x009ab960)
ENTRY(Grave_of_Saints, "Grave of Saints", 0x009dc6a0)
ENTRY(The_Gutter, "The Gutter", 0x009c6710)
ENTRY(Drangleic_Castle, "Drangleic Castle", 0x01346150)
ENTRY(Shrine_of_Amana, "Shrine of Amana", 0x0132dab0)
ENTRY(Undead_Crypt, "Undead Crypt", 0x0134d680)
ENTRY(Aldias_Keep, "Aldia's Keep", 0x009ae070)
ENTRY(Dragon_Aerie, "Dragon Aerie", 0x009cb530)
ENTRY(Shulva_Sanctum_City, "Shulva, Sanctum City", 0x030047b0)
ENTRY(Brume_Tower, "Brume Tower", 0x03006ec0)
ENTRY(Frozen_Eleum_Loyce, "Frozen Eleum Loyce", 0x030095d0)
