/*
 * Dark Souls 3 - Open Server
 * Copyright (C) 2021 Tim Leonard
 *
 * This program is free software; licensed under the MIT license.
 * You should have received a copy of the license along with this program.
 * If not, see <https://opensource.org/licenses/MIT>.
 */

ENTRY(Host, "Host", 0)
ENTRY(Hollow, "Hollow", -1)
ENTRY(While_Phantom, "While Phantom", 2)
ENTRY(Arbiter_Spirit, "Arbiter Spirit", 5)
ENTRY(Dark_Spirit, "Dark Spirit", 7)
ENTRY(Gray_Spirit, "Gray Spirit", 9)
ENTRY(Dragon_Spirit, "Dragon Spirit", 12)
ENTRY(Arena_Spirit, "Arena Spirit", 16)
ENTRY(Friendly_NPC, "Friendly NPC", 17)
ENTRY(Friendly_NPC_2, "Friendly NPC", 18)
ENTRY(Summoned_Friendly_NPC, "Summoned Friendly NPC", 20)
ENTRY(Hostility_NPC, "Hostility NPC", 23)
