/*
 * Dark Souls 3 - Open Server
 * Copyright (C) 2021 Tim Leonard
 *
 * This program is free software; licensed under the MIT license.
 * You should have received a copy of the license along with this program.
 * If not, see <https://opensource.org/licenses/MIT>.
 */

ENTRY(None,                                                       "None",                                                     0)

/*

0:Host
-1:Hollow
2:While Phantom
5:Arbiter Spirit
7:Dark Spirit
9:Gray Spirit
12:Dragon Spirit
16:Arena Spirit
17:Friendly NPC
18:Friendly NPC
20:Summoned Friendly NPC
23:Hostility NPC

*/