/*
 * Dark Souls 3 - Open Server
 * Copyright (C) 2021 Tim Leonard
 *
 * This program is free software; licensed under the MIT license.
 * You should have received a copy of the license along with this program.
 * If not, see <https://opensource.org/licenses/MIT>.
 */

ENTRY(Host,                                                       "Host",                                                     0)
ENTRY(Summon_1,                                                   "Summon 1",                                                 -1)
ENTRY(Summon_2,                                                   "Summon 2",                                                 -2)
ENTRY(Invade_1,                                                   "Invade",                                                   -3)
ENTRY(Summon_3,                                                   "Summon 3",                                                 -4)
ENTRY(Covenant_1,                                                 "Covenant 1",                                               -6)
ENTRY(Covenant_2,                                                 "Covenant 2",                                               -7)
ENTRY(Guardian_of_Rosaria,                                        "(Guardian of Rosaria)",                                    -8)
ENTRY(Covenant_3,                                                 "Covenant 3",                                               -9)
ENTRY(Covenant_4,                                                 "Covenant 4",                                               -10)
ENTRY(Avatar,                                                     "(Avatar)",                                                 -11)
ENTRY(Arena,                                                      "Arena",                                                    -12)
ENTRY(Umbasa_White,                                               "(Umbasa White)",                                           -13)
ENTRY(Summon_4,                                                   "Summon 4",                                                 -14)
ENTRY(Summon_5,                                                   "Summon 5",                                                 -15)
ENTRY(Summon_6,                                                   "Summon 6",                                                 -16)
ENTRY(Invade_2,                                                   "Invade 2",                                                 -17)
ENTRY(Invade_3,                                                   "Invade 3",                                                 -18)
ENTRY(Force_Join_Session,                                         "(Force Join Session)",                                     -19)
ENTRY(Red_Hunter,                                                 "(Red Hunter)",                                             -20)
ENTRY(Covenant_5,                                                 "Covenant 5",                                               -21)